{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "3e50be86",
   "metadata": {},
   "source": [
    "# Abaqus Script"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "88817688",
   "metadata": {},
   "outputs": [],
   "source": [
    "from abaqus import *\n",
    "from abaqusConstants import *\n",
    "import numpy as np\n",
    "\n",
    "mcfrp = {\n",
    "    \"name\": \"S-glass/Epoxy\", \"units\": \"MPa-mm-Mg\", \"type\": \"UD\", \"fiber\": \"S-glass\",\n",
    "    \"Vf\": 0.55, \"rho\": 2000E-12,\n",
    "    \"description\": \"Typical UD S-glass/Epoxy from TMM4175\",  \n",
    "    \"E1\": 48000, \"E2\": 11000, \"E3\": 11000, \n",
    "    \"v12\": 0.3, \"v13\": 0.3, \"v23\": 0.4, \n",
    "    \"G12\": 4200, \"G13\": 4200, \"G23\": 3600, \n",
    "    \"a1\": 4e-06, \"a2\": 2.0e-05, \"a3\": 2.0e-05, \n",
    "    \"XT\": 1300, \"YT\": 40, \"ZT\": 40,\n",
    "    \"XC\": 800, \"YC\": 140, \"ZC\": 140,\n",
    "    \"S12\": 70, \"S13\": 70, \"S23\": 40,\n",
    "    \"f12\":-0.5, \"f13\":-0.5, \"f23\":-0.5\n",
    "} \n",
    "\n",
    "\n",
    "def matlib(modelname):\n",
    "    mod = mdb.models[modelname]\n",
    "    \n",
    "    # Definerer material\n",
    "    mat = mod.Material(mcfrp['name'])\n",
    "    mat.Density(table=((mcfrp['rho'], ), ))\n",
    "    mat.Elastic(type=ENGINEERING_CONSTANTS, \n",
    "                table=((mcfrp['E1'], mcfrp['E2'], mcfrp['E3'], \n",
    "                        mcfrp['v12'], mcfrp['v13'], mcfrp['v23'], \n",
    "                        mcfrp['G12'], mcfrp['G13'], mcfrp['G23']), ))\n",
    "    mat.elastic.FailStress(table=((mcfrp['XT'], mcfrp['XC'], mcfrp['YT'], mcfrp['YC'], mcfrp['S12'], mcfrp['f12'], 0.0), ))\n",
    "\n",
    "\n",
    "def boxpro(modelname, L, b, h, t, n_spars, esize, applied_mass, profile=1):\n",
    "\n",
    "    # Define length from edge to point load\n",
    "    load_pos = (2.0 / 3.0) * L\n",
    "    # Correct h and b (due to offsetType = MIDDLE_SURFACE)\n",
    "    b -= t\n",
    "    h -= t\n",
    "\n",
    "    # Create model \n",
    "    mod = mdb.Model(name=modelname, modelType=STANDARD_EXPLICIT) \n",
    "    matlib(modelname)\n",
    "\n",
    "    # region Sketch \n",
    "    if profile == 1:\n",
    "        # ------- Outer Sketch ---------- \n",
    "        ske = mod.ConstrainedSketch(name='__profile__', sheetSize=200.0) \n",
    "        ske.rectangle(point1=(-b/2.0, -h/2.0), point2=(b/2.0, h/2.0)) \n",
    "\n",
    "\n",
    "        # ------- Inner Sketch ----------\n",
    "        \n",
    "        # Vertical Spars\n",
    "        if n_spars > 0:\n",
    "            spacing = b / (n_spars + 1)\n",
    "            x_pos = -b/2.0 + spacing\n",
    "            for _ in range(n_spars):\n",
    "                ske.Line(point1=(x_pos, h/2.0), point2=(x_pos, -h/2.0))\n",
    "                x_pos += spacing\n",
    "\n",
    "\n",
    "        # Calculate total length\n",
    "        total_length = 2*b + 2*h + n_spars*h\n",
    "        mass_factor = 550 # factor that will give simple box profile t=1\n",
    "        t = mass_factor / total_length # update t\n",
    "\n",
    "    elif profile == 2:\n",
    "        ske = mod.ConstrainedSketch(name='__profile__', sheetSize=200.0)\n",
    "        ske.Line(point1=(-b/2.0, h/2.0), point2=(b/2.0, h/2.0))\n",
    "\n",
    "        o1 = 10.0\n",
    "        o2 = 40.0\n",
    "\n",
    "        ske.Line(point1=(-b/2.0 + o1, h/2.0), point2=(-b/2.0 + o2, -h/2.0))\n",
    "        ske.Line(point1=(b/2.0 - o1, h/2.0), point2=(b/2.0 - o2, -h/2.0))\n",
    "        ske.Line(point1=(-b/2.0 + o2, -h/2.0), point2=(b/2.0 - o2, -h/2.0))\n",
    "\n",
    "        # Vertical Spars\n",
    "        if n_spars > 0:\n",
    "            spacing = (b - 2*o2) / (n_spars + 1)\n",
    "            x_pos = -b/2.0 + o2 + spacing\n",
    "            for _ in range(n_spars):\n",
    "                ske.Line(point1=(x_pos, h/2.0), point2=(x_pos, -h/2.0))\n",
    "                x_pos += spacing\n",
    "        \n",
    "        # Calculate total length\n",
    "        total_length = b + (b-2*o2) + 2*np.sqrt((o2-o1)**2 + h**2) + n_spars*h\n",
    "        mass_factor = 550 # factor that will give simple box profile t=1\n",
    "        t = mass_factor / total_length # update t \n",
    "\n",
    "    elif profile == 3:\n",
    "        pass # Legg til profil her\n",
    "\n",
    "\n",
    "    # Create part from sketch\n",
    "    prt = mod.Part(name='Box', dimensionality=THREE_D, type=DEFORMABLE_BODY)\n",
    "    prt.BaseShellExtrude(sketch=ske, depth=L)\n",
    "    del mod.sketches['__profile__']\n",
    "\n",
    "\n",
    "    # Partition for load surface\n",
    "    wheel_width = 0.1 * b + 0.1 # added small value \n",
    "    wheel_length = wheel_width * 2\n",
    "    id = prt.DatumPlaneByPrincipalPlane(principalPlane=YZPLANE, offset=(wheel_width)).id\n",
    "    prt.PartitionFaceByDatumPlane(datumPlane=prt.datums[id], faces=prt.faces)\n",
    "    id = prt.DatumPlaneByPrincipalPlane(principalPlane=YZPLANE, offset=(-wheel_width)).id\n",
    "    prt.PartitionFaceByDatumPlane(datumPlane=prt.datums[id], faces=prt.faces)\n",
    "\n",
    "    id = prt.DatumPlaneByPrincipalPlane(principalPlane=XYPLANE, offset=(load_pos + wheel_length)).id\n",
    "    prt.PartitionFaceByDatumPlane(datumPlane=prt.datums[id], faces=prt.faces)\n",
    "    id = prt.DatumPlaneByPrincipalPlane(principalPlane=XYPLANE, offset=(load_pos - wheel_length)).id\n",
    "    prt.PartitionFaceByDatumPlane(datumPlane=prt.datums[id], faces=prt.faces)\n",
    "\n",
    "    \"\"\"\n",
    "    # Material and section \n",
    "    mat = mod.Material(name='Alu')\n",
    "    mat.Density(table=((2.7E-9, ), ))\n",
    "    mat.Elastic(table=((70000.0, 0.33), ))\n",
    "    mod.HomogeneousShellSection(name='Section-shell', \n",
    "        preIntegrate=OFF, material='Alu', thicknessType=UNIFORM, thickness=t, \n",
    "        thicknessField='', nodalThicknessField='', \n",
    "        idealization=NO_IDEALIZATION, poissonDefinition=DEFAULT, \n",
    "        thicknessModulus=None, temperature=GRADIENT, useDensity=OFF, \n",
    "        integrationRule=SIMPSON, numIntPts=5)\n",
    "    region = prt.Set(faces=prt.faces, name='faces-all')\n",
    "    prt.SectionAssignment(region=region, sectionName='Section-shell', offset=0.0, \n",
    "        offsetType=MIDDLE_SURFACE, offsetField='', thicknessAssignment=FROM_SECTION)\n",
    "   \n",
    "   \"\"\"\n",
    "\n",
    "    # Mesh\n",
    "    prt.setMeshControls(regions=prt.faces, elemShape=QUAD, technique=STRUCTURED)\n",
    "    prt.seedPart(size=esize, deviationFactor=0.1, minSizeFactor=0.1)\n",
    "    prt.generateMesh()\n",
    "\n",
    "\n",
    "    # Assembly and constraints \n",
    "    ass = mod.rootAssembly\n",
    "    ass.DatumCsysByDefault(CARTESIAN)\n",
    "    ins = ass.Instance(name='Box', part=prt, dependent=ON)\n",
    "    ass.rotate(instanceList=('Box', ), axisPoint=(0.0, 0.0, 0.0), axisDirection=(0.0, 1.0, 0.0), angle=90.0)\n",
    "    ass.rotate(instanceList=('Box', ), axisPoint=(0.0, 0.0, 0.0), axisDirection=(1.0, 0.0, 0.0), angle=90.0)\n",
    "    rf1id = ass.ReferencePoint(point=(0.0, 0.0, 0.0)).id\n",
    "    rf2id = ass.ReferencePoint(point=(L, 0.0, 0.0)).id\n",
    "    regionRF1=ass.Set(referencePoints=(ass.referencePoints[rf1id],), name='RF1')\n",
    "    regionRF2=ass.Set(referencePoints=(ass.referencePoints[rf2id],), name='RF2')\n",
    "    edges1=ins.edges.getByBoundingBox(xMax=0.0)\n",
    "    region1 = ass.Set(edges=edges1, name = 'EDGES1')   \n",
    "    edges2=ins.edges.getByBoundingBox(xMin=L)\n",
    "    region2 = ass.Set(edges=edges2, name = 'EDGES2')   \n",
    "    mod.MultipointConstraint(name='Constraint-1', \n",
    "        controlPoint=regionRF1, surface=region1, mpcType=BEAM_MPC, \n",
    "        userMode=DOF_MODE_MPC, userType=0, csys=None)\n",
    "    mod.MultipointConstraint(name='Constraint-2', \n",
    "        controlPoint=regionRF2, surface=region2, mpcType=BEAM_MPC, \n",
    "        userMode=DOF_MODE_MPC, userType=0, csys=None)\n",
    "\n",
    "    # Steps, BC and loading\n",
    "    bc1 = mod.DisplacementBC(name='BC1', createStepName='Initial', \n",
    "        region=regionRF1, u1=SET, u2=SET, u3=SET, ur1=SET, ur2=SET, ur3=SET)\n",
    "    bc2 = mod.DisplacementBC(name='BC2', createStepName='Initial', \n",
    "        region=regionRF2, u1=SET, u2=SET, u3=SET, ur1=SET, ur2=SET, ur3=SET)\n",
    "\n",
    "    mod.BuckleStep(name='Step-Buck', previous='Initial', numEigen=2, vectors=4, maxIterations=700)\n",
    "    mod.StaticStep(name='Step-Stat', previous='Step-Buck') \n",
    "\n",
    "    \n",
    "    bc1.setValuesInStep(stepName='Step-Buck', \n",
    "        ur2=FREED, buckleCase=PERTURBATION_AND_BUCKLING)\n",
    "    bc1.setValuesInStep(stepName='Step-Stat', \n",
    "        ur2=FREED)\n",
    "    bc2.setValuesInStep(stepName='Step-Buck', \n",
    "        u1=FREED, u3=FREED, buckleCase=PERTURBATION_AND_BUCKLING)\n",
    "    bc2.setValuesInStep(stepName='Step-Stat', \n",
    "        u1=FREED, u3=FREED)\n",
    "    \n",
    "    # Create load surface\n",
    "    faces = ins.faces.getByBoundingBox(\n",
    "        xMin=load_pos-wheel_length, xMax=load_pos+wheel_length, \n",
    "        zMin=h/2.0, \n",
    "        yMax=wheel_width, yMin=-wheel_width\n",
    "    )\n",
    "    region3 = ass.Set(name='CONTACT-SURFACE', faces=faces)\n",
    "    \n",
    "    # Add inertia to load surface\n",
    "    ass.engineeringFeatures.NonstructuralMass(\n",
    "        name='Inertia-1', region=region3, units=TOTAL_MASS, magnitude=applied_mass, \n",
    "        distribution=MASS_PROPORTIONAL)\n",
    "\n",
    "    # Add gravity\n",
    "    mod.Gravity(name='Load-1', createStepName='Step-Buck', \n",
    "        comp3=-9810.0, distributionType=UNIFORM, field='')\n",
    "    mod.Gravity(name='Load-2', createStepName='Step-Stat', \n",
    "        comp3=-9810.0, distributionType=UNIFORM, field='')\n",
    "\n",
    "\n",
    "    # Job:\n",
    "    # job = mdb.Job(name=modelname, model=modelname)\n",
    "    # job.submit()\n",
    "\n",
    "    \n",
    "# boxpro(modelname='BP-1', L=1800, b=200, h=75, t=0.5, n_spars=0, esize=18, applied_mass=0.05, profile=2)\n",
    "boxpro(modelname='BP-2', L=1800, b=200, h=75, t=0.5, n_spars=1, esize=18, applied_mass=0.05, profile=2)\n",
    "# boxpro(modelname='BP-3', L=1800, b=200, h=75, t=0.5, n_spars=2, esize=18, applied_mass=0.05, profile=2)"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
