{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "b9c17cb7",
   "metadata": {},
   "source": [
    "# Abaqus Script"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c52a8373",
   "metadata": {},
   "outputs": [],
   "source": [
    "from abaqus import *\n",
    "from abaqusConstants import *\n",
    "import regionToolset\n",
    "\n",
    "def matlib(modelname):\n",
    "    mod = mdb.models[modelname]\n",
    "    mat = mod.Material('CFRP')\n",
    "    mat.Density(table=((1600e-12, ), ))\n",
    "    mat.Elastic(type=ENGINEERING_CONSTANTS, \n",
    "        table=((130000.0, 10000.0, 10000.0, 0.28, 0.28, 0.5, 4500.0, 4500.0, 3500.0,), ))\n",
    "    mat.elastic.FailStress(table=((1400.0, 900.0, 30.0, 120.0, 60.0, -0.5, 0.0), ))\n",
    "\n",
    "\n",
    "def joint_4(modelname, L, W, e, r, layup, esize, Nx, second_bolt=False):\n",
    "\n",
    "    # Create model and material\n",
    "    mod = mdb.Model(name=modelname)\n",
    "    matlib(modelname)\n",
    "\n",
    "    # --- Create Plate sketch with one or two bolt holes ---\n",
    "    ske = mod.ConstrainedSketch(name='__profile__', sheetSize=200.0)\n",
    "    ske.rectangle(point1=(0.0, 0.0), point2=(L, W))\n",
    "    # First bolt hole\n",
    "    ske.CircleByCenterPerimeter(\n",
    "        center=(e, W/2.0),\n",
    "        point1=(e + r, W/2.0)\n",
    "    )\n",
    "    # Second bolt hole if requested\n",
    "    if second_bolt:\n",
    "        ske.CircleByCenterPerimeter(\n",
    "            center=(2*e, W/2.0),\n",
    "            point1=(2*e + r, W/2.0)\n",
    "        )\n",
    "\n",
    "    prt = mod.Part(name='Plate', dimensionality=THREE_D, type=DEFORMABLE_BODY)\n",
    "    prt.BaseShell(sketch=ske)\n",
    "    del mod.sketches['__profile__']\n",
    "\n",
    "    # --- Partitioning for layup and joints ---\n",
    "    # Midplane for layup normal axis\n",
    "    dp = prt.DatumPlaneByPrincipalPlane(principalPlane=XZPLANE, offset=W/2.0)\n",
    "    prt.PartitionFaceByDatumPlane(datumPlane=prt.datums[dp.id], faces=prt.faces)\n",
    "    # Partition at x = e\n",
    "    dp = prt.DatumPlaneByPrincipalPlane(principalPlane=YZPLANE, offset=e)\n",
    "    prt.PartitionFaceByDatumPlane(datumPlane=prt.datums[dp.id], faces=prt.faces)\n",
    "    # Partition at x = 2e (second bolt)\n",
    "    if second_bolt:\n",
    "        dp = prt.DatumPlaneByPrincipalPlane(principalPlane=YZPLANE, offset=2*e)\n",
    "        prt.PartitionFaceByDatumPlane(datumPlane=prt.datums[dp.id], faces=prt.faces)\n",
    "\n",
    "    # Sets and surfaces for layup\n",
    "    regionAllFaces   = prt.Set(name='faces-all', faces=prt.faces)\n",
    "    normalAxisRegion = prt.Surface(side1Faces=prt.faces, name='SurfOuter')\n",
    "    primaryAxisRegion = prt.Set(\n",
    "        edges=prt.edges.findAt(((e/2.0, 0.0, 0.0),)),\n",
    "        name='edge-prim-axis'\n",
    "    )\n",
    "\n",
    "    # Composite layup\n",
    "    compLayup = prt.CompositeLayup(\n",
    "        name='LU', elementType=SHELL, offsetType=MIDDLE_SURFACE\n",
    "    )\n",
    "    compLayup.Section()\n",
    "    compLayup.ReferenceOrientation(\n",
    "        orientationType=DISCRETE, localCsys=None,\n",
    "        axis=AXIS_3, stackDirection=STACK_3,\n",
    "        normalAxisDefinition=SURFACE, normalAxisRegion=normalAxisRegion,\n",
    "        primaryAxisDefinition=EDGE, primaryAxisRegion=primaryAxisRegion,\n",
    "        primaryAxisDirection=AXIS_1\n",
    "    )\n",
    "    # Add plies\n",
    "    plyno = 1\n",
    "    for layer in layup:\n",
    "        reg = prt.sets[layer['region']]\n",
    "        compLayup.CompositePly(\n",
    "            suppressed=False,\n",
    "            plyName='Ply-' + str(plyno),\n",
    "            region=reg,\n",
    "            material=layer['mat'],\n",
    "            thicknessType=SPECIFY_THICKNESS,\n",
    "            thickness=layer['thi'],\n",
    "            orientationType=SPECIFY_ORIENT,\n",
    "            orientationValue=layer['ori'],\n",
    "            axis=AXIS_3,\n",
    "            numIntPoints=3\n",
    "        )\n",
    "\n",
    "        plyno += 1\n",
    "\n",
    "    # Mesh plate\n",
    "    prt.setMeshControls(regions=regionAllFaces.faces, elemShape=QUAD, technique=STRUCTURED)\n",
    "    prt.seedPart(size=esize)\n",
    "    prt.generateMesh()\n",
    "\n",
    "    # --- Assembly ---\n",
    "    ass = mod.rootAssembly\n",
    "    insPlate = ass.Instance(name='Plate', part=prt, dependent=ON)\n",
    "\n",
    "    # Create one Bolt part\n",
    "    ske = mod.ConstrainedSketch(name='__profile__', sheetSize=200.0)\n",
    "    ske.ConstructionLine(point1=(0.0, -100.0), point2=(0.0, 100.0))\n",
    "    ske.Line(point1=(r, -20.0), point2=(r, 20.0))\n",
    "    prtBolt = mod.Part(name='Bolt', dimensionality=THREE_D, type=ANALYTIC_RIGID_SURFACE)\n",
    "    prtBolt.AnalyticRigidSurfRevolve(sketch=ske)\n",
    "    del mod.sketches['__profile__']\n",
    "\n",
    "    # Bolt positions list\n",
    "    bolt_positions = [e]\n",
    "    if second_bolt:\n",
    "        bolt_positions.append(2*e)\n",
    "\n",
    "    # Loop to create bolt instances, contacts, RPs and BCs\n",
    "    for i, xpos in enumerate(bolt_positions, start=1):\n",
    "        inst_name = 'Bolt-' + str(i)\n",
    "        insBolt = ass.Instance(name=inst_name, part=prtBolt, dependent=ON)\n",
    "        ass.rotate(\n",
    "            instanceList=(inst_name,),\n",
    "            axisPoint=(0.0, 0.0, 0.0),\n",
    "            axisDirection=(1.0, 0.0, 0.0),\n",
    "            angle=90.0\n",
    "        )\n",
    "        ass.translate(\n",
    "            instanceList=(inst_name,),\n",
    "            vector=(xpos, W/2.0, 0.0)\n",
    "        )\n",
    "\n",
    "        # Contact interaction\n",
    "        region1 = ass.Surface(side2Faces=insBolt.faces, name='Surface-' + inst_name)\n",
    "        edges = insPlate.edges.getByBoundingCylinder(\n",
    "            center1=(xpos, W/2.0, -20.0),\n",
    "            center2=(xpos, W/2.0,  20.0),\n",
    "            radius=r\n",
    "        )\n",
    "        region2 = ass.Set(edges=edges, name='Edges-Hole-' + inst_name)\n",
    "        mod.ContactProperty('Contact-properties')\n",
    "        mod.SurfaceToSurfaceContactStd(\n",
    "            name='ContactBolt-' + str(i), createStepName='Initial',\n",
    "            main=region1, secondary=region2,\n",
    "            sliding=FINITE, thickness=ON,\n",
    "            interactionProperty='Contact-properties',\n",
    "            adjustMethod=NONE, initialClearance=OMIT, datumAxis=None, clearanceRegion=None\n",
    "        )\n",
    "\n",
    "        # Rigid body & BC\n",
    "        rp_id = ass.ReferencePoint(point=(xpos, W/2.0, 0.0)).id\n",
    "        regionRP = ass.Set(name='RP-' + str(i), referencePoints=(ass.referencePoints[rp_id],))\n",
    "        mod.RigidBody(\n",
    "            name='Constraint-Bolt-' + str(i),\n",
    "            refPointRegion=regionRP,\n",
    "            surfaceRegion=region1\n",
    "        )\n",
    "        mod.EncastreBC(\n",
    "            name='BC-FIX-' + str(i),\n",
    "            createStepName='Initial',\n",
    "            region=regionRP\n",
    "        )\n",
    "\n",
    "\n",
    "    # Support BCs on plate edges\n",
    "    edges = insPlate.edges.getByBoundingBox(xMax=0.0)\n",
    "    reg = ass.Set(name='edges at x=0', edges=edges)\n",
    "    mod.DisplacementBC(\n",
    "        name='support-z at x=0', createStepName='Initial',\n",
    "        region=reg, u3=SET\n",
    "    )\n",
    "    edges = insPlate.edges.getByBoundingBox(xMin=L)\n",
    "    reg   = ass.Set(name='edges at x=L', edges=edges)\n",
    "    sur   = ass.Surface(name='surface at x=L', side1Edges=edges)\n",
    "    mod.DisplacementBC(\n",
    "        name='support-z at x=L', createStepName='Initial',\n",
    "        region=reg, u3=SET\n",
    "    )\n",
    "\n",
    "    # Load step & outputs\n",
    "    mod.StaticStep(name='Step-1', previous='Initial')\n",
    "    mod.ShellEdgeLoad(\n",
    "        name='Nx', createStepName='Step-1',\n",
    "        region=sur, magnitude=Nx,\n",
    "        directionVector=((0.0, 0.0, 0.0), (1.0, 0.0, 0.0)),\n",
    "        distributionType=UNIFORM, traction=GENERAL\n",
    "    )\n",
    "    mod.FieldOutputRequest(\n",
    "        name='F-Output-2', createStepName='Step-1',\n",
    "        variables=('S','E','SE','SF','CFAILURE'),\n",
    "        layupNames=('Plate.LU',), layupLocationMethod=ALL_LOCATIONS,\n",
    "        rebar=EXCLUDE\n",
    "    )\n",
    "\n",
    "    # job = mdb.Job(name=modelname, model=modelname)\n",
    "    # job.submit()\n",
    "\n",
    "     \n",
    "layup1 = [ {'mat':'CFRP' , 'ori':  0  , 'thi':0.6, 'region': 'faces-all'},\n",
    "           {'mat':'CFRP' , 'ori':  0  , 'thi':0.6, 'region': 'faces-all'},\n",
    "           {'mat':'CFRP' , 'ori':  0  , 'thi':0.6, 'region': 'faces-all'},\n",
    "           {'mat':'CFRP' , 'ori':-45  , 'thi':0.6, 'region': 'faces-all'},\n",
    "           {'mat':'CFRP' , 'ori': 45  , 'thi':0.6, 'region': 'faces-all'},\n",
    "           {'mat':'CFRP' , 'ori':  0  , 'thi':0.6, 'region': 'faces-all'},\n",
    "           {'mat':'CFRP' , 'ori':  0  , 'thi':0.6, 'region': 'faces-all'},\n",
    "           {'mat':'CFRP' , 'ori':  0  , 'thi':0.6, 'region': 'faces-all'},\n",
    "           {'mat':'CFRP' , 'ori': 45  , 'thi':0.6, 'region': 'faces-all'},\n",
    "           {'mat':'CFRP' , 'ori':-45  , 'thi':0.6, 'region': 'faces-all'},\n",
    "           {'mat':'CFRP' , 'ori':  0  , 'thi':0.6, 'region': 'faces-all'},\n",
    "           {'mat':'CFRP' , 'ori':  0  , 'thi':0.6, 'region': 'faces-all'},\n",
    "           {'mat':'CFRP' , 'ori':  0  , 'thi':0.6, 'region': 'faces-all'} ]\n",
    "\n",
    "\n",
    "\n",
    "# joint_4(modelname='A4', L=1000, W=100, e=50, r=10, layup=layup1, esize=5, Nx=1000, second_bolt=False)\n",
    "# joint_4(modelname='A4', L=1000, W=100, e=50, r=10, layup=layup1, esize=5, Nx=1000, second_bolt=True)\n",
    "joint_4(modelname='A4', L=1000, W=100/2, e=50, r=10, layup=layup1, esize=5, Nx=1000, second_bolt=False)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
